### PR TITLE
Fix resource warning.

### LINKED ISSUE #176: `ResourceWarning: unclosed file` when running test suite via tox
```
<doctest wsgi.rst[73]>:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmpofj91v_5buildoutSetUp/_TEST_/sample-buildout/parts/instance/etc/wsgi.ini' mode='r' encoding='UTF-8'>
  wsgi_ini = open(os.path.join(instance, 'etc', 'wsgi.ini')).read()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

Not sure whether this could be related to #152

full output
```
 tox -r -e py38
py38 recreate: /home/jugmac00/Projects/plone.recipe.zope2instance/.tox/py38
py38 installdeps: -rrequirements-testing-zope-4.txt, coverage
py38 develop-inst: /home/jugmac00/Projects/plone.recipe.zope2instance
py38 installed: AccessControl==4.2,Acquisition==4.7,AuthEncoding==4.2,beautifulsoup4==4.9.3,BTrees==4.7.2,certifi==2021.5.30,cffi==1.14.6,Chameleon==3.9.0,coverage==5.5,DateTime==4.3,DocumentTemplate==3.4,ExtensionClass==4.5.0,MultiMapping==4.1,multipart==0.1.1,Paste==3.5.0,PasteDeploy==2.1.1,Persistence==3.0,persistent==4.6.4,-e git+git@github.com:plone/plone.recipe.zope2instance@067935008262eab720f21bbe1f0f8d5c6b38375a#egg=plone.recipe.zope2instance,pycparser==2.20,python-dotenv==0.19.0,python-gettext==4.0,pytz==2021.1,RestrictedPython==5.1,roman==3.3,sentry-sdk==1.3.1,six==1.15.0,soupsieve==2.2.1,transaction==3.0.1,urllib3==1.26.6,waitress==1.4.4,WebOb==1.8.6,WebTest==2.0.35,WSGIProxy2==0.4.6,z3c.pt==3.3.0,zc.buildout==2.13.4,zc.lockfile==2.0,zc.recipe.egg==2.0.7,ZConfig==3.5.0,zdaemon==4.3,ZEO==5.2.2,zExceptions==4.1,ZODB==5.6.0,zodbpickle==2.0.0,Zope==4.5.5,zope.annotation==4.7.0,zope.browser==2.3,zope.browsermenu==4.4,zope.browserpage==4.4.0,zope.browserresource==4.4,zope.cachedescriptors==4.3.1,zope.component==4.6.2,zope.configuration==4.4.0,zope.container==4.4.0,zope.contentprovider==4.2.1,zope.contenttype==4.5.0,zope.deferredimport==4.3.1,zope.deprecation==4.4.0,zope.dottedname==4.3,zope.event==4.5.0,zope.exceptions==4.4,zope.filerepresentation==5.0.0,zope.globalrequest==1.5,zope.hookable==5.0.1,zope.i18n==4.7.0,zope.i18nmessageid==5.0.1,zope.interface==5.2.0,zope.lifecycleevent==4.3,zope.location==4.2,zope.pagetemplate==4.5.0,zope.processlifetime==2.3.0,zope.proxy==4.3.5,zope.ptresource==4.2.0,zope.publisher==6.0.0,zope.schema==6.1.0,zope.security==5.1.1,zope.sequencesort==4.1.2,zope.site==4.4.0,zope.size==4.3,zope.structuredtext==4.3,zope.tal==4.4,zope.tales==5.1,zope.testbrowser==5.5.1,zope.testing==4.7,zope.testrunner==5.2,zope.traversing==4.4.1,zope.viewlet==4.2.1
py38 run-test-pre: PYTHONHASHSEED='1144400110'
py38 run-test: commands[0] | coverage run /home/jugmac00/Projects/plone.recipe.zope2instance/.tox/py38/bin/zope-testrunner --test-path=src
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
<doctest wsgi.rst[73]>:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmp_sitw8cibuildoutSetUp/_TEST_/sample-buildout/parts/instance/etc/wsgi.ini' mode='r' encoding='UTF-8'>
  wsgi_ini = open(os.path.join(instance, 'etc', 'wsgi.ini')).read()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
  Ran 17 tests with 0 failures, 0 errors and 0 skipped in 3 minutes 2.809 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
_____________________________________________ summary ______________________________________________
  py38: commands succeeded
  congratulations :)
```

### PR DESCRIPTION
**Pull request by icemac**
Fixes #176

### CODE REVIEW

**Comment by icemac** [comment]
@jenkins-plone-org please run jobs

**Comment by icemac** [comment]
I see no need for a change log entry for such a minor fix in the tests.
I ran `tox` locally on Python 3.8 and do not see the `ResourceWarning` any more.

**Review by mauritsvanrees — APPROVED** [review]
LGTM, thanks!

Looks like the GitHub Actions are not running because the repository has been inactive lately. I have re-enabled it and triggered a run on master. I will close the PR and reopen it to see if that trigger actions.

**Comment by mauritsvanrees** [comment]
I am agreed that no changelog entry is needed.
And all Jenkins tests passed, but the package is not tested there.

Locally, `tox -e py39` fails, but that is because it tries to install Zope 4. The GitHub Actions have been setup to do this correctly. Should be doable to fix `tox.ini`, but that is not for this PR.

Actions are not triggered yet. I have [triggered them manually](https://github.com/plone/plone.recipe.zope2instance/actions/runs/1138702807) now for this branch. Let's see. Can be merged if they are green.

**Comment by mauritsvanrees** [comment]
The actions are green, I merge.

**Pull request merged**
