### PR TITLE
fix windows cluster f.. config

### PR DESCRIPTION
**Pull request by jensens**
listen need to be configurable, also added missing features

### CODE REVIEW

**Comment by jensens** [comment]
The robot failure in 5.2/3.6 seems to be unreleated.

**Review by mauritsvanrees — APPROVED** [review]
LGTM. Thanks!

**Comment by mauritsvanrees** [comment]
Released as  6.8.3. I will update coredev shortly. I always wait a few minutes so PyPI mirrors are updated.

**Comment by jensens** [comment]
Huh, this merge broke the GH actions tests on master - but OTOH in here all been green.

**Pull request merged**
