### PR TITLE
Set the default for the http-fast-listen to on to match the documentation

### PR DESCRIPTION
**Pull request by ale-rt**
Refs. #71

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
Thanks for the review :+1: I am going to implement the changes

**Comment by ale-rt** [comment]
@mauritsvanrees when you were refering to the `wsgi_options` you meant something like this, right? https://github.com/plone/plone.recipe.zope2instance/pull/143/commits/1d2a842ef177fa80ff7be72163bbd6ae72526166

**Comment by mauritsvanrees** [comment]
@ale-rt Yes, that is what I meant.

One test failure remaining on Travis, only on 2.7 apparently, which is a bit strange.

**Comment by ale-rt** [comment]
The Python 2.7 failure is related to ZServer, I am on it

**Comment by ale-rt** [comment]
Finally (when ZServer is not a thing anymore) the comment that suggests to set `fast-listen` to `off` appears also when `fast-listen` is not already set to `off`... :man_facepalming: 
```
# Set to off to defer opening of the HTTP socket until the end of the
# startup phase:
fast-listen on
```

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
I rerun the jenkins test even if they are not actually testing this package. When they are complete I will merge this

**Pull request merged**
