### PR TITLE
Add Sentry support

### PR DESCRIPTION
**Pull request by tschorr**
This PR adds basic Sentry support using the Python Sentry SDK as documented in https://docs.sentry.io/platforms/python/logging/.

### CODE REVIEW

**Comment by tschorr** [comment]
@jenkins-plone-org please run jobs

**Comment by zopyx** [comment]
@tschorr I have an alternative implementation here:

https://github.com/collective/collective.sentry

How would you log the Zope specific request information as it is present in the standard error_log?

https://github.com/collective/collective.sentry/blob/master/collective/sentry/error_handler.py#L57-L74

**Comment by tschorr** [comment]
@zopyx thanks for the pointer, I didn't know about collective.sentry. As mentionned above, this PR is adding basic logging support, nothing Zope specific yet. I agree adding information from the Zope Request would be a plus. But I also think sentry configuration should go into the wsgi.ini, since this is the place were all the other logging is configured. And I like the idea of offering basic Sentry support with p.r.zope2instance.

**Comment by zopyx** [comment]
collective.sentry is less than a week old...I will check out PR.

**Pull request merged**
