### PR TITLE
repair incomplete commit from last PR (sry)

### PR DESCRIPTION
**Pull request by dhavlik**
note to self: when using "commit suggestion" feature of github, keep in mind that there might be more than one such button.
note to self 2: thoroughly test stuff before filing a PR

### CODE REVIEW

**Comment by icemac** [comment]
@jenkins-plone-org please run jobs

**Comment by dhavlik** [comment]
@jenkins-plone-org please run jobs

**Comment by icemac** [comment]
@dhavlik Maybe changing the change log entry of the last PR can trick the change log verifier.

**Comment by dhavlik** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
I have released 6.4.0 with this.
Thanks!

**Comment by icemac** [comment]
@mauritsvanrees Thank you!

**Pull request merged**
