### PR TITLE
Restore file based logging for waitress

### PR DESCRIPTION
**Pull request by tschorr**
The WSGI setup currently doesn't write any logfiles (it logs to the console only). This PR tries to restore at least basic logging options for access and event log.

### CODE REVIEW

**Comment by tschorr** [comment]
@jenkins-plone-org please run jobs

**Comment by tschorr** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Comment by pbauer** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
