### PR TITLE
Python 3 compatibility.

### PR DESCRIPTION
**Pull request by tlotze**
Simultaneous Python 2 and 3 compatibility.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
I see you have signed the contributor agreement. Good. Welcome!
Now we need to run the tests on the Jenkins server.
You can start jobs for them yourself, instructions are here: http://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html
I have started them now.

Oh, but they immediately start failing:

```
 print(msg, file=sys.stderr)
                   ^
SyntaxError: invalid syntax
```

So this needs fixing.
And I see a note by github: 'This branch has conflicts that must be resolved.' So you will want to rebase your branch on master.

BTW, the master branch is still used on Plone 4.3, which means it must support Python 2.6. I can imagine that it is tricky to support 2.6, 2.7, and Python 3. It is nice if this works, but I don't think anyone will mind if we split off a maintenance branch for Plone 4.3. So if it works on 2.7 but fails on 2.6 this is fine with me.

**Comment by jensens** [comment]
+1 for split old to a 4.x branch and new major version 5.0

**Comment by gforcada** [comment]
@icemac @tlotze maybe you have some time to finish this porting? :-) we would then be one step closer to have official support of backups on python 3 😄

**Comment by icemac** [comment]
@gforcada I looked into the Python 3 support it turns out that it needs Simplistix/mailinglogger#4 to be fixed and released in the first place as `mailinglogger 3.8.0` cannot even be installed on Python 3. Are you planning to look into it again?

**Comment by gforcada** [comment]
@icemac I tried twice to get that running, but I did not have enough time to finish it, I left this PR thought: https://github.com/Simplistix/mailinglogger/pull/11

**Comment by tschorr** [comment]
`mailinglogger` is not strictly necessary for this package, only if you use the `mailinglogger` option you will require the package in your buildout.

**Comment by tschorr** [comment]
Current Jenkins failure seems unrelated.

**Pull request merged**
