### PR TITLE
Allow to customize the WSGI pipeline 

### LINKED ISSUE #116: Customizing the WSGI pipeline
It would be cool to customize the pipeline so that some middleware can be used for whatever reason.
One immediate example is to use the https://github.com/hathawsh/slowlog middleware as an immediately working and available replacement for `Products.LongRequestLogger` in Python 3:
see https://github.com/zopefoundation/Products.LongRequestLogger/issues/4

### PR DESCRIPTION
**Pull request by ale-rt**
Fixes #116

### CODE REVIEW

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by mamico** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
