### PR TITLE
Fix tox by telling pip to disregard pyproject.toml

### LINKED ISSUE #98: Builds are failing on TravisCI
See https://travis-ci.org/plone/plone.recipe.zope2instance

The reason seems to be the `pyproject.toml` file which makes `pip` think it should use instead of `setup.py`.

### PR DESCRIPTION
**Pull request by dataflake**
Fixes #98

### CODE REVIEW

**Comment by dataflake** [comment]
The best solution would be to move those `towncrier` settings into `setup.cfg`, where everyone else in the world puts settings, and then get rid of `pyproject.toml` altogether. I don't know if `towncrier` supports that. (I don't even know why `towncrier` is used at all, seems like a whole bunch of inconvenience just to maintain a change log)

**Comment by mauritsvanrees** [comment]
No, towncrier does not support reading `setup.cfg` files.

Discussion and reasons for towncrier can be found on this [thread on community.plone.org](https://community.plone.org/t/using-towncrier-for-changes-rst-in-plone-packages/6486).  Occasionally it causes headaches, but mostly it avoids headaches. For me it is a win.

AFAIK, `pyproject.toml` is meant as the new standard for putting settings that you would until now put into `setup.cfg`. It is just silly that `pip` decided to break development installs on the basis that this file exists. And apparently this was an unintended side effect, which is reverted on master.

**Comment by dataflake** [comment]
Thanks for the explanation! And I do appreciate the fast turnaround today.

**Comment by mauritsvanrees** [comment]
O, and for laughs, `pip` itself is also using `towncrier`, which is how I learned of its existence a year ago. :-)
It has a [pyproject.toml](https://github.com/pypa/pip/blob/master/pyproject.toml#L1-L2) file with towncrier settings and with these lines:

```
[build-system]
requires = ["setuptools", "wheel"]
```

I briefly tried if adding these lines to the `pyproject.toml` in `plone.recipe.zope2instance` helped, but it did not: you still need the `--no-use-pep517` flag.
The `pip` folks seem to have [fixed](https://github.com/pypa/pip/commit/21b759315fae5f8c91ca22322a05b18e12f838fe) this in their `tox.ini` by removing the `usedevelop = True` line. I guess that indeed helps for tox, but is not nice for local development.

**Pull request merged**
