### PR TITLE
Remove duplicate word.

### PR DESCRIPTION
**Pull request by jugmac00**

### CODE REVIEW

**Comment by jugmac00** [comment]
> @jugmac00 you need to sign the Plone Contributor Agreement in order to merge this pull request.
> 
> Learn about the Plone Contributor Agreement: http://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html

I'll sign it next Monday. Got no printer at home :-(

**Comment by jugmac00** [comment]
I submitted/sent the contributor's agreement today.

The build currently fails due to pip-gate, cf 
https://github.com/pypa/pip/issues/6434
https://discuss.python.org/t/pip-19-1-and-installing-in-editable-mode-with-pyproject-toml/1553/39

I'd suggest to wait a couple of days until the pip maintainers offer a proper solution.

**Comment by mauritsvanrees** [comment]
I have merged PR #102 which fixes the Travis problem. Can you rebase your branch on master or merge the master changes and try again?

**Comment by jugmac00** [comment]
@mauritsvanrees Thanks for merging!

And yes, I know it was not strictly necessary, as similar rules apply for contributing to Zope - which I do since last year's **Zope 4 Welcome Sprint** and especially since **Saltlabs sprint – Zope and Plone together**.

I inherited quite a big Zope installation which happens to use a couple of Plone packages, including this recipe. So it certainly does not hurt to have the agreement signed. You'll never know what comes :-)

**Pull request merged**
